---

- name: Install rabbitmq
  command: kubectl apply -f -
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'configmap.yml') }}"
    - "{{ lookup('template', 'role.yml') }}"
    - "{{ lookup('template', 'rolebinding.yml') }}"
    - "{{ lookup('template', 'secret.yml') }}"
    - "{{ lookup('template', 'service.yml') }}"
    - "{{ lookup('template', 'serviceaccount.yml') }}"
    - "{{ lookup('template', 'persistentvolume.yml') }}"
    - "{{ lookup('template', 'statefulset.yml') }}"
