{% for volume in rabbitmq_persistent_volumes %}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv{{ loop.index }}
  labels:
    type: local
    app: rabbitmq
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  {{ volume | to_nice_yaml(indent=2) | indent(2) }}
{% endfor %}