kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv1
  labels:
    type: local
    app: rabbitmq
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/rabbitmq-pv1"