apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
type: Opaque
data:
  rabbitmq-password: "{{ rabbitmq_password | b64encode }}"
  rabbitmq-erlang-cookie: "{{ rabbitmq_erlang_cookie | b64encode }}"