apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ rabbitmq_manager_port }}
      targetPort: http
    - name: amqp
      protocol: TCP
      port: {{ rabbitmq_amqp_port }}
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: {{ rabbitmq_epmd_port }}
      targetPort: epmd
  selector:
    app: rabbitmq
  type: ClusterIP